from app import db
import datetime

class User(db.Model):
    """
    微信公众的会员
    """
    id = db.Column(db.Integer, primary_key=True)
    openid = db.Column(db.String(64),nullable=True, comment='openid')
    nickname = db.Column(db.String(64), comment='微信昵称')
    sex = db.Column(db.Integer, comment='用户性别')
    province = db.Column(db.String(64), comment='省份')
    city = db.Column(db.String(64), comment='城市')
    country = db.Column(db.String(64), comment='国家')
    headimgurl = db.Column(db.String(256), comment='用户头像')
    privilege = db.Column(db.String(64), comment='用户特权信息')
    unionid = db.Column(db.String(64), comment='unionid')
    mobile = db.Column(db.String(128), nullable=True, comment='手机号')
    category = db.Column(db.String(255),nullable=True, comment='品类')
    shopurl = db.Column(db.String(255), nullable=True,comment='店铺URL')
    memo = db.Column(db.String(255), nullable=True,comment='备忘录')
    expiredate = db.Column(db.Date, nullable=True, comment='有效期')
    signdate = db.Column(db.Date, default=datetime.date.today ,nullable=True,comment='注册会员日期')
    audit = db.Column(db.Integer, default=0,comment='是否提交主管审核:1 true , 0 false')
    ismember = db.Column(db.Integer, default=0,comment='是不是会员')
    ywyname = db.Column(db.String(255), nullable=True,comment='业务员姓名')
    kol_tag1 = db.Column(db.String(20), comment='允许查看标签')
    kol_tag2 = db.Column(db.String(20), comment='允许查看标签')
    kol_tag3 = db.Column(db.String(20), comment='允许查看标签')
    name = db.Column(db.String(20), comment='客户姓名')
    supplier = db.Column(db.String(30), comment='供应商')
    shop = db.Column(db.String(50), comment='店铺名')
    tag_update_time = db.Column(db.DateTime, default=datetime.datetime.now,comment='标签修改时间')
    update_num = db.Column(db.Integer, default=0,comment='修改次数')

class Cmm0(db.Model):
    __tablename__ = 'cmm_0'
    ID = db.Column(db.INTEGER, primary_key=True,)
    promotion_id = db.Column(db.BIGINT,comment='商品ID')
    author_number = db.Column(db.INTEGER,comment='昨日热推达人数')
    brand_name = db.Column(db.String(255),comment='品牌名')
    coupon_price = db.Column(db.Float,comment='折后单价')
    day_order_count = db.Column(db.INTEGER,comment='昨日售量')
    image = db.Column(db.String(255),comment='图片')
    market_price = db.Column(db.Float,comment='市场价')
    money = db.Column(db.Float,comment='每单佣金')
    month_conversion_rate = db.Column(db.Float,comment='30日抖音转化率')
    order_count = db.Column(db.INTEGER,comment='抖音月销量')
    platform = db.Column(db.String(255),comment='在售平台')
    rank = db.Column(db.INTEGER,comment='昨日排行')
    rate = db.Column(db.Float,comment='每单佣金百分比')
    sale_incr = db.Column(db.INTEGER,comment='淘客月销量增量')
    sales = db.Column(db.INTEGER,comment='淘宝月销量')
    shop_name = db.Column(db.String(255),comment='店名')
    title = db.Column(db.String(255),comment='商品标题')
    category = db.Column(db.String(255),comment='类目')
    time = db.Column(db.Date,comment='日期')

class Cmm1(db.Model):
    __tablename__ = 'cmm_1'
    ID = db.Column(db.INTEGER, primary_key=True, )
    promotion_id = db.Column(db.BIGINT, comment='商品ID')
    author_number = db.Column(db.INTEGER, comment='昨日热推达人数')
    brand_name = db.Column(db.String(255), comment='品牌名')
    coupon_price = db.Column(db.Float, comment='折后单价')
    day_order_count = db.Column(db.INTEGER, comment='昨日售量')
    image = db.Column(db.String(255), comment='图片')
    market_price = db.Column(db.Float, comment='市场价')
    money = db.Column(db.Float, comment='每单佣金')
    month_conversion_rate = db.Column(db.Float, comment='30日抖音转化率')
    order_count = db.Column(db.INTEGER, comment='抖音月销量')
    platform = db.Column(db.String(255), comment='在售平台')
    rank = db.Column(db.INTEGER, comment='昨日排行')
    rate = db.Column(db.Float, comment='每单佣金百分比')
    sale_incr = db.Column(db.INTEGER, comment='淘客月销量增量')
    sales = db.Column(db.INTEGER, comment='淘宝月销量')
    shop_name = db.Column(db.String(255), comment='店名')
    title = db.Column(db.String(255), comment='商品标题')
    category = db.Column(db.String(255), comment='类目')
    time = db.Column(db.Date, comment='日期')

class Cmm2(db.Model):
    __tablename__ = 'cmm_2'
    ID = db.Column(db.INTEGER, primary_key=True, )
    promotion_id = db.Column(db.BIGINT, comment='商品ID')
    author_number = db.Column(db.INTEGER, comment='昨日热推达人数')
    brand_name = db.Column(db.String(255), comment='品牌名')
    coupon_price = db.Column(db.Float, comment='折后单价')
    day_order_count = db.Column(db.INTEGER, comment='昨日售量')
    image = db.Column(db.String(255), comment='图片')
    market_price = db.Column(db.Float, comment='市场价')
    money = db.Column(db.Float, comment='每单佣金')
    month_conversion_rate = db.Column(db.Float, comment='30日抖音转化率')
    order_count = db.Column(db.INTEGER, comment='抖音月销量')
    platform = db.Column(db.String(255), comment='在售平台')
    rank = db.Column(db.INTEGER, comment='昨日排行')
    rate = db.Column(db.Float, comment='每单佣金百分比')
    sale_incr = db.Column(db.INTEGER, comment='淘客月销量增量')
    sales = db.Column(db.INTEGER, comment='淘宝月销量')
    shop_name = db.Column(db.String(255), comment='店名')
    title = db.Column(db.String(255), comment='商品标题')
    category = db.Column(db.String(255), comment='类目')
    time = db.Column(db.Date, comment='日期')

class Cmm3(db.Model):
    __tablename__ = 'cmm_3'
    ID = db.Column(db.INTEGER, primary_key=True, )
    promotion_id = db.Column(db.BIGINT, comment='商品ID')
    author_number = db.Column(db.INTEGER, comment='昨日热推达人数')
    brand_name = db.Column(db.String(255), comment='品牌名')
    coupon_price = db.Column(db.Float, comment='折后单价')
    day_order_count = db.Column(db.INTEGER, comment='昨日售量')
    image = db.Column(db.String(255), comment='图片')
    market_price = db.Column(db.Float, comment='市场价')
    money = db.Column(db.Float, comment='每单佣金')
    month_conversion_rate = db.Column(db.Float, comment='30日抖音转化率')
    order_count = db.Column(db.INTEGER, comment='抖音月销量')
    platform = db.Column(db.String(255), comment='在售平台')
    rank = db.Column(db.INTEGER, comment='昨日排行')
    rate = db.Column(db.Float, comment='每单佣金百分比')
    sale_incr = db.Column(db.INTEGER, comment='淘客月销量增量')
    sales = db.Column(db.INTEGER, comment='淘宝月销量')
    shop_name = db.Column(db.String(255), comment='店名')
    title = db.Column(db.String(255), comment='商品标题')
    category = db.Column(db.String(255), comment='类目')
    time = db.Column(db.Date, comment='日期')

class Cmm4(db.Model):
    __tablename__ = 'cmm_4'
    ID = db.Column(db.INTEGER, primary_key=True, )
    promotion_id = db.Column(db.BIGINT, comment='商品ID')
    author_number = db.Column(db.INTEGER, comment='昨日热推达人数')
    brand_name = db.Column(db.String(255), comment='品牌名')
    coupon_price = db.Column(db.Float, comment='折后单价')
    day_order_count = db.Column(db.INTEGER, comment='昨日售量')
    image = db.Column(db.String(255), comment='图片')
    market_price = db.Column(db.Float, comment='市场价')
    money = db.Column(db.Float, comment='每单佣金')
    month_conversion_rate = db.Column(db.Float, comment='30日抖音转化率')
    order_count = db.Column(db.INTEGER, comment='抖音月销量')
    platform = db.Column(db.String(255), comment='在售平台')
    rank = db.Column(db.INTEGER, comment='昨日排行')
    rate = db.Column(db.Float, comment='每单佣金百分比')
    sale_incr = db.Column(db.INTEGER, comment='淘客月销量增量')
    sales = db.Column(db.INTEGER, comment='淘宝月销量')
    shop_name = db.Column(db.String(255), comment='店名')
    title = db.Column(db.String(255), comment='商品标题')
    category = db.Column(db.String(255), comment='类目')
    time = db.Column(db.Date, comment='日期')

class Cmm5(db.Model):
    __tablename__ = 'cmm_5'
    ID = db.Column(db.INTEGER, primary_key=True, )
    promotion_id = db.Column(db.BIGINT, comment='商品ID')
    author_number = db.Column(db.INTEGER, comment='昨日热推达人数')
    brand_name = db.Column(db.String(255), comment='品牌名')
    coupon_price = db.Column(db.Float, comment='折后单价')
    day_order_count = db.Column(db.INTEGER, comment='昨日售量')
    image = db.Column(db.String(255), comment='图片')
    market_price = db.Column(db.Float, comment='市场价')
    money = db.Column(db.Float, comment='每单佣金')
    month_conversion_rate = db.Column(db.Float, comment='30日抖音转化率')
    order_count = db.Column(db.INTEGER, comment='抖音月销量')
    platform = db.Column(db.String(255), comment='在售平台')
    rank = db.Column(db.INTEGER, comment='昨日排行')
    rate = db.Column(db.Float, comment='每单佣金百分比')
    sale_incr = db.Column(db.INTEGER, comment='淘客月销量增量')
    sales = db.Column(db.INTEGER, comment='淘宝月销量')
    shop_name = db.Column(db.String(255), comment='店名')
    title = db.Column(db.String(255), comment='商品标题')
    category = db.Column(db.String(255), comment='类目')
    time = db.Column(db.Date, comment='日期')

class Cmm6(db.Model):
    __tablename__ = 'cmm_6'
    ID = db.Column(db.INTEGER, primary_key=True, )
    promotion_id = db.Column(db.BIGINT, comment='商品ID')
    author_number = db.Column(db.INTEGER, comment='昨日热推达人数')
    brand_name = db.Column(db.String(255), comment='品牌名')
    coupon_price = db.Column(db.Float, comment='折后单价')
    day_order_count = db.Column(db.INTEGER, comment='昨日售量')
    image = db.Column(db.String(255), comment='图片')
    market_price = db.Column(db.Float, comment='市场价')
    money = db.Column(db.Float, comment='每单佣金')
    month_conversion_rate = db.Column(db.Float, comment='30日抖音转化率')
    order_count = db.Column(db.INTEGER, comment='抖音月销量')
    platform = db.Column(db.String(255), comment='在售平台')
    rank = db.Column(db.INTEGER, comment='昨日排行')
    rate = db.Column(db.Float, comment='每单佣金百分比')
    sale_incr = db.Column(db.INTEGER, comment='淘客月销量增量')
    sales = db.Column(db.INTEGER, comment='淘宝月销量')
    shop_name = db.Column(db.String(255), comment='店名')
    title = db.Column(db.String(255), comment='商品标题')
    category = db.Column(db.String(255), comment='类目')
    time = db.Column(db.Date, comment='日期')

class Cmm7(db.Model):
    __tablename__ = 'cmm_7'
    ID = db.Column(db.INTEGER, primary_key=True, )
    promotion_id = db.Column(db.BIGINT, comment='商品ID')
    author_number = db.Column(db.INTEGER, comment='昨日热推达人数')
    brand_name = db.Column(db.String(255), comment='品牌名')
    coupon_price = db.Column(db.Float, comment='折后单价')
    day_order_count = db.Column(db.INTEGER, comment='昨日售量')
    image = db.Column(db.String(255), comment='图片')
    market_price = db.Column(db.Float, comment='市场价')
    money = db.Column(db.Float, comment='每单佣金')
    month_conversion_rate = db.Column(db.Float, comment='30日抖音转化率')
    order_count = db.Column(db.INTEGER, comment='抖音月销量')
    platform = db.Column(db.String(255), comment='在售平台')
    rank = db.Column(db.INTEGER, comment='昨日排行')
    rate = db.Column(db.Float, comment='每单佣金百分比')
    sale_incr = db.Column(db.INTEGER, comment='淘客月销量增量')
    sales = db.Column(db.INTEGER, comment='淘宝月销量')
    shop_name = db.Column(db.String(255), comment='店名')
    title = db.Column(db.String(255), comment='商品标题')
    category = db.Column(db.String(255), comment='类目')
    time = db.Column(db.Date, comment='日期')

class Cmm8(db.Model):
    __tablename__ = 'cmm_8'
    ID = db.Column(db.INTEGER, primary_key=True, )
    promotion_id = db.Column(db.BIGINT, comment='商品ID')
    author_number = db.Column(db.INTEGER, comment='昨日热推达人数')
    brand_name = db.Column(db.String(255), comment='品牌名')
    coupon_price = db.Column(db.Float, comment='折后单价')
    day_order_count = db.Column(db.INTEGER, comment='昨日售量')
    image = db.Column(db.String(255), comment='图片')
    market_price = db.Column(db.Float, comment='市场价')
    money = db.Column(db.Float, comment='每单佣金')
    month_conversion_rate = db.Column(db.Float, comment='30日抖音转化率')
    order_count = db.Column(db.INTEGER, comment='抖音月销量')
    platform = db.Column(db.String(255), comment='在售平台')
    rank = db.Column(db.INTEGER, comment='昨日排行')
    rate = db.Column(db.Float, comment='每单佣金百分比')
    sale_incr = db.Column(db.INTEGER, comment='淘客月销量增量')
    sales = db.Column(db.INTEGER, comment='淘宝月销量')
    shop_name = db.Column(db.String(255), comment='店名')
    title = db.Column(db.String(255), comment='商品标题')
    category = db.Column(db.String(255), comment='类目')
    time = db.Column(db.Date, comment='日期')

class Cmm9(db.Model):
    __tablename__ = 'cmm_9'
    ID = db.Column(db.INTEGER, primary_key=True, )
    promotion_id = db.Column(db.BIGINT, comment='商品ID')
    author_number = db.Column(db.INTEGER, comment='昨日热推达人数')
    brand_name = db.Column(db.String(255), comment='品牌名')
    coupon_price = db.Column(db.Float, comment='折后单价')
    day_order_count = db.Column(db.INTEGER, comment='昨日售量')
    image = db.Column(db.String(255), comment='图片')
    market_price = db.Column(db.Float, comment='市场价')
    money = db.Column(db.Float, comment='每单佣金')
    month_conversion_rate = db.Column(db.Float, comment='30日抖音转化率')
    order_count = db.Column(db.INTEGER, comment='抖音月销量')
    platform = db.Column(db.String(255), comment='在售平台')
    rank = db.Column(db.INTEGER, comment='昨日排行')
    rate = db.Column(db.Float, comment='每单佣金百分比')
    sale_incr = db.Column(db.INTEGER, comment='淘客月销量增量')
    sales = db.Column(db.INTEGER, comment='淘宝月销量')
    shop_name = db.Column(db.String(255), comment='店名')
    title = db.Column(db.String(255), comment='商品标题')
    category = db.Column(db.String(255), comment='类目')
    time = db.Column(db.Date, comment='日期')

class CmmAll(db.Model):
    ID = db.Column(db.INTEGER, primary_key=True, )
    promotion_id = db.Column(db.BIGINT, comment='商品ID')
    author_number = db.Column(db.INTEGER, comment='昨日热推达人数')
    brand_name = db.Column(db.String(255), comment='品牌名')
    coupon_price = db.Column(db.Float, comment='折后单价')
    day_order_count = db.Column(db.INTEGER, comment='昨日售量')
    image = db.Column(db.String(255), comment='图片')
    market_price = db.Column(db.Float, comment='市场价')
    money = db.Column(db.Float, comment='每单佣金')
    month_conversion_rate = db.Column(db.Float, comment='30日抖音转化率')
    order_count = db.Column(db.INTEGER, comment='抖音月销量')
    platform = db.Column(db.String(255), comment='在售平台')
    rank = db.Column(db.INTEGER, comment='昨日排行')
    rate = db.Column(db.Float, comment='每单佣金百分比')
    sale_incr = db.Column(db.INTEGER, comment='淘客月销量增量')
    sales = db.Column(db.INTEGER, comment='淘宝月销量')
    shop_name = db.Column(db.String(255), comment='店名')
    title = db.Column(db.String(255), comment='商品标题')
    category = db.Column(db.String(255), comment='类目')
    time = db.Column(db.Date, comment='日期')

class Header(db.Model):
    promotion_id = db.Column(db.INTEGER, primary_key=True)
    sales = db.Column(db.INTEGER, comment='淘宝月销量')
    market_price = db.Column(db.Float, comment='市场价/100')
    price = db.Column(db.Float, comment='淘宝价/100')
    video_count = db.Column(db.INTEGER, comment='近30日种草视频量')
    time = db.Column(db.Date, comment='截止时间')
    title = db.Column(db.String(100), comment='标题')
    url = db.Column(db.String(255), comment='链接')
    image = db.Column(db.String(255), comment='图片')
    product_platform = db.Column(db.String(20), comment='平台')
    coupon_web_url = db.Column(db.String(255), comment='优惠券地址')
    tb_coupon_info = db.Column(db.String(30), comment='优惠券标题')
    tb_max_commission_rate = db.Column(db.Float, comment='淘宝每单佣金比例')
    tb_volume = db.Column(db.INTEGER, comment='淘宝成交总计')
    tb_coupon_remain_count = db.Column(db.INTEGER, comment='淘宝优惠券领取总计')
    tb_coupon_price = db.Column(db.Float, comment='淘宝券后价格')
    brand_name = db.Column(db.String(30), comment='品牌名')
    estimated_commission = db.Column(db.Float, comment='每单佣金')
    comment_count = db.Column(db.INTEGER, comment='淘宝累计评论')
    product_desc = db.Column(db.Float, comment='描述')
    shop_id = db.Column(db.INTEGER, comment='淘宝店铺id')
    shop_name = db.Column(db.String(30), comment='淘宝店铺名称')
    douyin_conversion_rate = db.Column(db.Float, comment='昨日抖音转化率')
    month_conversion_rate = db.Column(db.Float, comment='近30日抖音转化率')
    star_list = db.Column(db.Text, comment='热推达人')

class KolList(db.Model):

    id = db.Column(db.INTEGER, primary_key=True)
    nickname = db.Column(db.String(255), comment='昵称')
    userid = db.Column(db.BIGINT, unique=True, comment='用户id')
    follower_num = db.Column(db.INTEGER, comment='粉丝数')
    tag = db.Column(db.String(255), comment='类别')
    video_count = db.Column(db.INTEGER, comment='总作品数')
    avg_interaction_15 = db.Column(db.INTEGER, comment='近15天平均互动量')
    age = db.Column(db.INTEGER, comment='年龄')
    sex = db.Column(db.String(255), comment='性别')
    Fans_description = db.Column(db.String(255), comment='用户描述')
    mcn_name = db.Column(db.String(255), comment='机构名称')
    douyin_id = db.Column(db.String(255), comment='抖音ID')
    cooperate_index = db.Column(db.Float, comment='合作指数')
    growth_index = db.Column(db.Float, comment='涨粉指数')
    spread_index = db.Column(db.Float, comment='传播指数')
    cp_index = db.Column(db.Float, comment='性价比指数')
    shopping_index = db.Column(db.Float, comment='种草指数')
    star_map_index = db.Column(db.Float, comment='星图指数')

    fans_attribute = db.relationship('FansAttribute', uselist=False)
    phone_age_info = db.relationship('PhoneAgeInfo', uselist=False)
    region = db.relationship('Region', uselist=False)

class FansAttribute(db.Model):
    __tablename__ = 'fans_attributes'
    userid = db.Column(db.ForeignKey('kol_list.userid'), primary_key=True)
    avg_play = db.Column(db.Float(asdecimal=True), comment='平均播放量')
    avg_like = db.Column(db.Float(asdecimal=True), comment='平均点赞量')
    avg_comment = db.Column(db.Float(asdecimal=True), comment='平均评论量')
    total_video_count = db.Column(db.BigInteger, comment='累计作品数')
    video_count_15 = db.Column(db.BigInteger, comment='近15天作品数')
    video_count_30 = db.Column(db.BigInteger, comment='近30天作品数')
    total_video_avg_interaction = db.Column(db.Float(asdecimal=True), comment='累计作品平均互动量')
    avg_interaction_15 = db.Column(db.Float(asdecimal=True), comment='近15天平均互动量')
    avg_interaction_30 = db.Column(db.Float(asdecimal=True), comment='近30天平均互动量')
    avatar = db.Column(db.String(255), comment='达人头像')

    kol = db.relationship('KolList')

# 手机年龄信息
class PhoneAgeInfo(db.Model):
    __tablename__ = 'phone_age_info'
    userid = db.Column(db.ForeignKey('kol_list.userid', ondelete='CASCADE', onupdate='CASCADE'), primary_key=True)
    iPhone = db.Column(db.BigInteger, comment='苹果')
    OPPO = db.Column(db.BigInteger, comment='oppo')
    vivo = db.Column(db.BigInteger, comment='vivo')
    others = db.Column(db.BigInteger, comment='其他品牌手机')
    huawei = db.Column(db.BigInteger, comment='华为')
    xiaomi = db.Column(db.BigInteger, comment='小米')
    less_18 = db.Column(db.BigInteger, comment='小于18岁')
    age_18_25 = db.Column(db.BigInteger, comment='18到25岁')
    age_26_32 = db.Column(db.BigInteger, comment='26到32岁')
    age_33_39 = db.Column(db.BigInteger, comment='33到39岁')
    age_40_46 = db.Column(db.BigInteger, comment='40到46岁')
    greater_46 = db.Column(db.BigInteger, comment='大于46岁')
    male = db.Column(db.BigInteger, comment='男')
    female = db.Column(db.BigInteger, comment='女')
    one_city = db.Column(db.Float(asdecimal=True), comment='一线城市')   #Float float(当asdecimal=True时，强制转换为decimal.Decimal对象) 浮点型
    two_city = db.Column(db.Float(asdecimal=True), comment='二线城市')
    three_city = db.Column(db.Float(asdecimal=True), comment='三线城市')

    kol = db.relationship('KolList')

# 地域
class Region(db.Model):
    __tablename__ = 'region'
    userid = db.Column(db.ForeignKey('kol_list.userid', ondelete='CASCADE', onupdate='CASCADE'), primary_key=True)
    qingh = db.Column(db.BigInteger, comment='青海')
    heil = db.Column(db.BigInteger, comment='河南')
    shangd = db.Column(db.BigInteger, comment='山东')
    sic = db.Column(db.BigInteger, comment='四川')
    jiangs = db.Column(db.BigInteger, comment='江苏')
    guiz = db.Column(db.BigInteger, comment='贵州')
    xingj = db.Column(db.BigInteger, comment='新疆')
    fuj = db.Column(db.BigInteger, comment='福建')
    zhej = db.Column(db.BigInteger, comment='浙江')
    hub = db.Column(db.BigInteger, comment='湖北')
    tianj = db.Column(db.BigInteger, comment='天津')
    jiangx = db.Column(db.BigInteger, comment='江西')
    xiz = db.Column(db.BigInteger, comment='西藏')
    heilj = db.Column(db.BigInteger, comment='黑龙江')
    guangd = db.Column(db.BigInteger, comment='广东')
    yunn = db.Column(db.BigInteger, comment='云南')
    beij = db.Column(db.BigInteger, comment='北京')
    taiw = db.Column(db.BigInteger, comment='台湾')
    aom = db.Column(db.BigInteger, comment='澳门')
    guangx = db.Column(db.BigInteger, comment='广西')
    shan3x = db.Column(db.BigInteger, comment='陕西')
    gans = db.Column(db.BigInteger, comment='甘肃')
    heb = db.Column(db.BigInteger, comment='河北')
    ningx = db.Column(db.BigInteger, comment='宁夏')
    chongq = db.Column(db.BigInteger, comment='重庆')
    jil = db.Column(db.BigInteger, comment='吉林')
    hun = db.Column(db.BigInteger, comment='湖南')
    neimg = db.Column(db.BigInteger, comment='内蒙古')
    anh = db.Column(db.BigInteger, comment='安徽')
    xiangg = db.Column(db.BigInteger, comment='香港')
    shangh = db.Column(db.BigInteger, comment='上海')
    shan1x = db.Column(db.BigInteger, comment='山西')
    hain = db.Column(db.BigInteger, comment='海南')
    liaon = db.Column(db.BigInteger, comment='辽宁')

    kol = db.relationship('KolList')

class AgeSexRegion(db.Model):
    promotion_id = db.Column(db.BigInteger, primary_key=True)
    age_6_17 = db.Column(db.INTEGER, comment='年龄分布')
    age_18_24 = db.Column(db.INTEGER, comment='年龄分布')
    age_25_30 = db.Column(db.INTEGER, comment='年龄分布')
    age_31_35 = db.Column(db.INTEGER, comment='年龄分布')
    age_36_40 = db.Column(db.INTEGER, comment='年龄分布')
    age_41 = db.Column(db.INTEGER, comment='年龄分布')
    time = db.Column(db.Date, comment='日期')
    city_0 = db.Column(db.String(255), comment='城市')
    city_1 = db.Column(db.String(255))
    city_2 = db.Column(db.String(255))
    city_3 = db.Column(db.String(255))
    city_4 = db.Column(db.String(255))
    city_5 = db.Column(db.String(255))
    city_5 = db.Column(db.String(255))
    city_7 = db.Column(db.String(255))
    city_8 = db.Column(db.String(255))
    city_9 = db.Column(db.String(255))
    province_0 = db.Column(db.String(255))
    city_0_pct = db.Column(db.Float)
    province_0_pct = db.Column(db.Float, comment='省份占比排第一的百分比')
    province_1 = db.Column(db.String(255))
    city_1_pct = db.Column(db.Float)
    province_1_pct = db.Column(db.Float)
    province_2 = db.Column(db.String(255))
    city_2_pct = db.Column(db.Float)
    province_2_pct = db.Column(db.Float)
    province_3 = db.Column(db.String(255))
    city_3_pct = db.Column(db.Float)
    province_3_pct = db.Column(db.Float)
    province_4 = db.Column(db.String(255))
    city_4_pct = db.Column(db.Float)
    province_4_pct = db.Column(db.Float)
    province_5 = db.Column(db.String(255))
    city_5_pct = db.Column(db.Float)
    province_5_pct = db.Column(db.Float)
    province_6 = db.Column(db.String(255))
    city_6_pct = db.Column(db.Float)
    province_6_pct = db.Column(db.Float)
    province_7 = db.Column(db.String(255))
    city_7_pct = db.Column(db.Float)
    province_7_pct = db.Column(db.Float)
    province_8 = db.Column(db.String(255))
    city_8_pct = db.Column(db.Float)
    province_8_pct = db.Column(db.Float)
    province_9 = db.Column(db.String(255))
    city_9_pct = db.Column(db.Float)
    province_9_pct = db.Column(db.Float)

class Basic(db.Model):
    promotion_id = db.Column(db.BigInteger, primary_key=True)
    time = db.Column(db.Date)
    basic = db.Column(db.TEXT)

class Permission(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    url = db.Column(db.String(255), comment='允许访问的url')
    title = db.Column(db.String(20), comment='权限简介')

class Role(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(20), comment='角色简介')